#! /env/bin/bash

option="$1"
shift 1

clean () {

    sudo find . -exec touch {} +
}

install () {

    python -m venv .venv

    source .venv/bin/activate

    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt -r requirements.dev.txt

    deactivate
}

test (){

    source .venv/bin/activate
    cd src
    python -m pytest -v
    cd ..
    deactivate
}


yoke () {

    source .venv/bin/activate
    python src/entrypoint.py "$@"
    deactivate
}

usage () {
    echo "-----------------------------------------------"
    echo "yoke - llm harness"
    echo "-----------------------------------------------"
    echo "usage:"
    echo
    echo ". cli [ arp-scan | clean | install | test | yoke ]"
    echo
    echo
    echo ". cli arp-scan [interface]"
}

arp_scan () {
    sudo arp-scan --interface="$1" --localnet
}

case "$option" in

    clean)
        clean "$@"
    ;;

    install)
        install
    ;;

    arp-scan)
        arp_scan "$@"
    ;;

    help)
        usage
    ;;

    test)
        test
    ;;

    *)
        yoke "$@"
    ;;

esac
